services:
  pre-config:
    image: busybox
    networks:
      - app-network
    volumes:
      - ./dial/config:/mnt/config
      - ./tools:/mnt/tools
      - ./.env.core:/mnt/.env.core
    entrypoint: [ "/bin/sh", "-c", "sh /mnt/tools/update-dial-config.sh" ]

  themes:
    image: epam/ai-dial-chat-themes:0.4.1
    networks:
      - app-network
    ports:
      - "3001:8080"

  chat:
    # image: epam/ai-dial-chat:0.13.1
    build: https://github.com/WEAIDiscovery/ai-dial-chat.git#feat/actions
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - themes
      - core
    env_file: .env.chat
    environment:
      THEMES_CONFIG_HOST: "http://themes:8080"
      DIAL_API_HOST: "http://core:8080"
      ENABLED_FEATURES: "conversations-section,prompts-section,top-settings,top-clear-conversation,top-chat-info,top-chat-model-settings,empty-chat-settings,header,footer,report-an-issue,likes,input-files,attachments-manager"

  redis:
    image: redis:7.2.4-alpine3.19
    networks:
      - app-network
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 2000mb
      --maxmemory-policy volatile-lfu
      --save ""
      --appendonly no
      --loglevel warning
    mem_limit: 2200M

  core:
    image: epam/ai-dial-core:0.12.0
    networks:
      - app-network
    ports:
      - "8080:8080"
    env_file: .env.core
    environment:
      AIDIAL_SETTINGS: '/opt/settings/settings.json'
      JAVA_OPTS: '-Dgflog.config=/opt/settings/gflog.xml'
      aidial.config.files: '["/opt/config/config.json"]'
      aidial.storage.overrides: '{ "jclouds.filesystem.basedir": "data" }'
      aidial.redis.singleServerConfig.address: 'redis://redis:6379'
    depends_on:
      - redis
      - pre-config
    volumes:
      - ${DIAL_DIR:-.}/dial/settings:/opt/settings
      - ${DIAL_DIR:-.}/dial/config:/opt/config
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -S http://0.0.0.0:8080/health 2>&1 | grep '200 OK' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20

  adapter-openai:
    image: epam/ai-dial-adapter-openai:0.12.0
    networks:
      - app-network
    environment:
      WEB_CONCURRENCY: "3"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -S http://0.0.0.0:5000/health 2>&1 | grep '200 OK' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 20

  dial-app:
    build: app
    networks:
      - app-network
    env_file: .env.app
    ports:
      - "5002:5002"
    depends_on:
      core:
        condition: service_healthy
      adapter-openai:
        condition: service_healthy
      redis:
        condition: service_started

networks:
  app-network:
    driver: bridge
