services:
  pre-config:
    image: busybox
    volumes:
      - ./dial/config:/mnt/config
      - ./tools:/mnt/tools
      - ./.env.core:/mnt/.env.core
    entrypoint: [ "/bin/sh", "-c", "sh /mnt/tools/update-dial-config.sh" ]

  themes:
    image: epam/ai-dial-chat-themes:0.4.1
    ports:
      - "3001:8080"

  chat:
    ports:
      - "3000:3000"
    image: epam/ai-dial-chat:0.13.1
    depends_on:
      - themes
      - core
    env_file: .env.chat
    environment:
      THEMES_CONFIG_HOST: "http://themes:8080"
      DIAL_API_HOST: "http://core:8080"
      ENABLED_FEATURES: "conversations-section,prompts-section,top-settings,top-clear-conversation,top-chat-info,top-chat-model-settings,empty-chat-settings,header,foiter,report-an-issue,likes,input-files,attachments-manager"

  redis:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 2000mb
      --maxmemory-policy volatile-lfu
      --save ""
      --appendonly no
      --loglevel warning
    mem_limit: 2200M

  core:
    user: ${UID:-root}
    ports:
      - "8080:8080"
    image: epam/ai-dial-core:0.12.0
    env_file: .env.core
    environment:
      'AIDIAL_SETTINGS': '/opt/settings/settings.json'
      'JAVA_OPTS': '-Dgflog.config=/opt/settings/gflog.xml'
      'LOG_DIR': '/app/log'
      'STORAGE_DIR': '/app/data'
      'aidial.config.files': '["/opt/config/config.json"]'
      'aidial.storage.overrides': '{ "jclouds.filesystem.basedir": "data" }'
      'aidial.redis.singleServerConfig.address': 'redis://redis:6379'
      'DIAL_DIR': '.'
    depends_on:
      - redis
      - pre-config
    volumes:
      - ${DIAL_DIR:-.}/dial/settings:/opt/settings
      - ${DIAL_DIR:-.}/dial/config:/opt/config
      - ${DIAL_DIR:-.}/dial/logs/:/app/log
      - ${DIAL_DIR:-.}/dial/data/:/app/data

  adapter-openai:
    image: epam/ai-dial-adapter-openai:0.12.0
    environment:
      WEB_CONCURRENCY: "3"

  dial-app:
    build: app
    env_file: .env.app
    ports:
      - "5002:5002"
